// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

    "chat": {
      name: "chat",
      type: "registry:ui",
      registryDependencies: ["button","https://shadcn-chatbot-kit.vercel.app/r/use-auto-scroll.json","https://shadcn-chatbot-kit.vercel.app/r/chat-message.json","https://shadcn-chatbot-kit.vercel.app/r/message-input.json","https://shadcn-chatbot-kit.vercel.app/r/message-list.json","https://shadcn-chatbot-kit.vercel.app/r/prompt-suggestions.json"],
      files: ["registry/default/ui/chat.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/chat.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-auto-scroll": {
      name: "use-auto-scroll",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-auto-scroll.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-auto-scroll.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message": {
      name: "chat-message",
      type: "registry:ui",
      registryDependencies: ["button","https://shadcn-chatbot-kit.vercel.app/r/copy-button.json","https://shadcn-chatbot-kit.vercel.app/r/markdown-renderer.json"],
      files: ["registry/default/ui/chat-message.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/chat-message.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy-button": {
      name: "copy-button",
      type: "registry:ui",
      registryDependencies: ["button","https://shadcn-chatbot-kit.vercel.app/r/use-copy-to-clipboard.json"],
      files: ["registry/default/ui/copy-button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/copy-button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-copy-to-clipboard": {
      name: "use-copy-to-clipboard",
      type: "registry:hook",
      registryDependencies: ["sonner"],
      files: ["registry/default/hooks/use-copy-to-clipboard.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-copy-to-clipboard.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "markdown-renderer": {
      name: "markdown-renderer",
      type: "registry:ui",
      registryDependencies: ["https://shadcn-chatbot-kit.vercel.app/r/copy-button.json"],
      files: ["registry/default/ui/markdown-renderer.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/markdown-renderer.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "message-input": {
      name: "message-input",
      type: "registry:ui",
      registryDependencies: ["button","https://shadcn-chatbot-kit.vercel.app/r/use-autosize-textarea.json"],
      files: ["registry/default/ui/message-input.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/message-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-autosize-textarea": {
      name: "use-autosize-textarea",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-autosize-textarea.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-autosize-textarea.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "message-list": {
      name: "message-list",
      type: "registry:ui",
      registryDependencies: ["https://shadcn-chatbot-kit.vercel.app/r/chat-message.json","https://shadcn-chatbot-kit.vercel.app/r/typing-indicator.json"],
      files: ["registry/default/ui/message-list.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/message-list.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typing-indicator": {
      name: "typing-indicator",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/typing-indicator.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/typing-indicator.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "prompt-suggestions": {
      name: "prompt-suggestions",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/prompt-suggestions.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/prompt-suggestions.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-demo": {
      name: "chat-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "message-input-demo": {
      name: "message-input-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/message-input-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/message-input-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message-demo": {
      name: "chat-message-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-message-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-message-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "message-list-demo": {
      name: "message-list-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/message-list-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/message-list-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typing-indicator-demo": {
      name: "typing-indicator-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typing-indicator-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typing-indicator-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "markdown-renderer-demo": {
      name: "markdown-renderer-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/markdown-renderer-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/markdown-renderer-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "prompt-suggestions-demo": {
      name: "prompt-suggestions-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/prompt-suggestions-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/prompt-suggestions-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy-button-demo": {
      name: "copy-button-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/copy-button-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/copy-button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message-animations-demo": {
      name: "chat-message-animations-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-message-animations-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-message-animations-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message-actions-demo": {
      name: "chat-message-actions-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-message-actions-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-message-actions-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message-timestamp-demo": {
      name: "chat-message-timestamp-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-message-timestamp-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-message-timestamp-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "chat-message-custom-styling-demo": {
      name: "chat-message-custom-styling-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/chat-message-custom-styling-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/chat-message-custom-styling-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy-button-custom-message-demo": {
      name: "copy-button-custom-message-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/copy-button-custom-message-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/copy-button-custom-message-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy-button-code-block-demo": {
      name: "copy-button-code-block-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/copy-button-code-block-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/copy-button-code-block-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
}
